### ISSUE TITLE
Anything-but wildcard support seems to still not work

### ISSUE THREAD

**Issue by HackityAnn** [aws/event-ruler#152] opened 2024-04-02 15:54 UTC
## Describe the bug
Although it was merged [here](https://github.com/aws/event-ruler/pull/145) I am still getting an InvalidEventPatternException when trying to use wildcard with anything-but

## To Reproduce
Try to create the eventrule with:
```
          "input": [
                {
                "anything-but": [
                    {"wildcard": "*\"AWS_STEP_FUNCTIONS_STARTED_BY_EXECUTION_ID\":*"}
                    ]
                }
            ]
```
## Expected behavior
Would expect this to filter within the input field for anything-but my wildcard expression (in this case if it is a child of a step function)

## Environment:
AWS eu-west-1

**Comment by jonessha** [comment] 2024-04-02 16:19
It looks like the problem is you're using square brackets after the anything-but, whereas you should be using curly brackets. Like in the README example:

```
{
  "detail": {
    "state": [ { "anything-but": { "wildcard": "*/bin/*.jar" } } ]
  }
}
```

It also sounds like you might be looking for this functionality in AWS. Perhaps in EventBridge? Although we aim to deploy all new Ruler functionality in AWS, the time this takes varies based on service, and it is far from instantaneous today. If you're looking at EventBridge specifically, then anything-but-wildcard support may be available in a month or two, and we will publish a What's New post to indicate when it is available.

Closing this but please re-open if you still believe anything-but-wildcard is not working as expected.

**Closed by jonessha** 2024-04-02 16:19 UTC
Labels: bug

**Comment by HackityAnn** [comment] 2024-04-02 16:48
Ah you are right I am dumb sorry!

**Comment by jonessha** [comment] 2024-04-02 17:33
Not at all, no worries!
